// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deliver/deliver.proto

package deliver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_45756aee656274fa, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "deliver.Msg")
}

func init() { proto.RegisterFile("deliver/deliver.proto", fileDescriptor_45756aee656274fa) }

var fileDescriptor_45756aee656274fa = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x49, 0xcd, 0xc9,
	0x2c, 0x4b, 0x2d, 0xd2, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x38, 0x17, 0xb3, 0x6f, 0x71, 0xba, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0xba, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x69, 0x64, 0xc6, 0xc5, 0xee, 0x02, 0x51, 0x23, 0xa4, 0x8d,
	0x60, 0xf2, 0xe8, 0xc1, 0xcc, 0xf1, 0x2d, 0x4e, 0x97, 0x42, 0xe1, 0x29, 0x31, 0x68, 0x30, 0x1a,
	0x30, 0x3a, 0xa9, 0x44, 0x29, 0xa5, 0xe7, 0x17, 0xe4, 0x24, 0x56, 0xea, 0xa7, 0xe7, 0xeb, 0x16,
	0x15, 0x24, 0xc3, 0x2c, 0xd6, 0x4d, 0x47, 0xe2, 0x24, 0xb1, 0x81, 0x9d, 0x61, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x56, 0x3c, 0x76, 0xec, 0x9f, 0x00, 0x00, 0x00,
}
